title: LMS Website
description: > # this means to ignore newlines until "baseurl:"
  Website description
  asd
url: "http://yourdomain.com" # the base hostname & protocol for your site

collections:
  courses:
    permalink: /courses/:path/
    output: true
